id: PB493EF94
initial_creation_type: input
source_metadata:
  title: Vajrasattva Series
  language: en
  description: 'A series of texts related to the deity Vajrasattva (rdo rje sems dpa''):'
  volume:
    54217a4ae73341eba021e752c35aa91a:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Confession
    ba0172f3eb0d47ccaf678eb5ea01af1b:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Guru Yoga
    1a53b86d7efd48efbd2ff2207ca37c5b:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    72d9dd9245bc471fb1b1c5b34dbc07a9:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Practices
    7d0fb6dc3be147b78d747b6619c40e1b:
      title: A Song of Innermost Praise to Vajrasattva
      parent: Praise
    87489383424540b184f9b4781c7532a1:
      title: 'Wish-Granting Provision of Twofold Accomplishment: A Praise of Vajrasattva'
      parent: Praise
    607fe7d6bd5a4266a1543c152d979471:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    42bd705788f140b4b78eb9d23b406dad:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    18d9a7373aea43f7b9b67fdf08c1e5d6:
      title: Brief Vajrasattva Visualisation and Mantra Recitation
      parent: Sādhanas
    3b5e8f6b0be34193b1acfbcf7a34028f:
      title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the
        Glorious Vajrasattva, a Method of Purification and Accomplishment for Both
        Self and Others'
      parent: Sādhanas
created_at: '2022-03-01T06:32:25.083446'
last_modified_at: '2022-03-01T06:32:25.083452'
